language: python
python:
- '2.7'
before_script:
- cd ..
- wget http://googleappengine.googlecode.com/files/google_appengine_1.8.8.zip
- unzip google_appengine_1.8.8.zip
- rm google_appengine_1.8.8.zip
- sudo apt-get install python-imaging
install:
- sudo pip install -r requirements.txt --use-mirrors
- sudo pip install nose
- sudo pip install WebTest
- sudo pip install nosegae
script:
- git clone https://github.com/slowsoul/NewTictactoe.git deploy
- cd deploy
- /usr/local/bin/nosetests
after_success:
- google_appengine/appcfg.py --oauth2_refresh_token=$MY_GAE_TOKEN update deploy/
env:
  global:
    secure: rnjgCGsZeuKcx7rngDwN3u3WbIyKlE4mSBI1II//AkFH0WO2OMVredw0K86UU3cVoy7wfAm0lwAKRT8SG2HiRCs/EgqJSym0hIBlvK75104oWfs8XAd7SpdFU7PBT0dog64iGS9A10xp4zxdqaC1+9KAnH8TC10UKMWjsRgec28=
